=== boltboyy/Java_labs_4a/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "number": {
        "type": "string",
        "minLength": 1
      },
      "surname": {
        "type": "string",
        "minLength": 1
      },
      "name": {
        "type": "string",
        "minLength": 1
      },
      "patronymic": {
        "type": "string",
        "minLength": 1
      },
      "group": {
        "type": "string",
        "minLength": 1
      },
      "faculty": {
        "type": "string",
        "minLength": 1
      },
      "sessions": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "number": {
              "type": "integer",
              "minimum": 1,
              "maximum": 9
            },
            "course": {
              "type": "integer",
              "minimum": 1,
              "maximum": 6
            },
            "averageMark": {
              "type": "number"
            },
            "exams": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "subject": {
                    "type": "string",
                    "minLength": 1
                  },
                  "mark": {
                    "type": "integer",
                    "minimum": 1,
                    "maximum": 10
                  }
                },
                "required": [
                  "subject",
                  "mark"
                ],
                "additionalProperties": false
              }
            },
            "credits": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "subject": {
                    "type": "string",
                    "minLength": 1
                  },
                  "passed": {
                    "type": "boolean"
                  }
                },
                "required": [
                  "subject",
                  "passed"
                ],
                "additionalProperties": false
              }
            }
          },
          "required": [
            "number",
            "course",
            "exams",
            "credits"
          ],
          "additionalProperties": false
        }
      }
    },
    "required": [
      "number",
      "name",
      "surname",
      "patronymic",
      "group",
      "faculty",
      "sessions"
    ],
    "additionalProperties": false
  }
}

=== boltboyy/Java_labs_4a/gradebook.json
[ {
  "number" : "0002",
  "surname" : "Иванов",
  "name" : "Иван",
  "patronymic" : "Иванович",
  "group" : "05a",
  "faculty" : "ФПМИ",
  "sessions" : [ {
    "number" : 1,
    "course" : 1,
    "exams" : [ {
      "subject" : "Математика",
      "mark" : 8
    }, {
      "subject" : "Физика",
      "mark" : 7
    }, {
      "subject" : "Химия",
      "mark" : 8
    } ],
    "credits" : [ {
      "subject" : "Физкультура",
      "passed" : true
    } ],
    "averageMark" : 7.666666666666667
  }, {
    "number" : 2,
    "course" : 1,
    "exams" : [ {
      "subject" : "Математика",
      "mark" : 10
    }, {
      "subject" : "Информатика",
      "mark" : 5
    } ],
    "credits" : [ {
      "subject" : "Физкультура",
      "passed" : true
    } ],
    "averageMark" : 7.5
  } ]
}, {
  "number" : "0003",
  "surname" : "Сидоров",
  "name" : "Семен",
  "patronymic" : "Семенович",
  "group" : "05б",
  "faculty" : "ФПМИ",
  "sessions" : [ {
    "number" : 1,
    "course" : 1,
    "exams" : [ {
      "subject" : "Математика",
      "mark" : 6
    }, {
      "subject" : "Физика",
      "mark" : 7
    } ],
    "credits" : [ {
      "subject" : "Физкультура",
      "passed" : true
    } ],
    "averageMark" : 6.5
  }, {
    "number" : 2,
    "course" : 1,
    "exams" : [ {
      "subject" : "Математика",
      "mark" : 3
    }, {
      "subject" : "Информатика",
      "mark" : 5
    } ],
    "credits" : [ {
      "subject" : "Физкультура",
      "passed" : false
    } ],
    "averageMark" : 4.0
  } ]
}, {
  "number" : "0001",
  "surname" : "Петров",
  "name" : "Петр",
  "patronymic" : "Петрович",
  "group" : "05a",
  "faculty" : "ФПМИ",
  "sessions" : [ {
    "number" : 1,
    "course" : 1,
    "exams" : [ {
      "subject" : "Математика",
      "mark" : 9
    }, {
      "subject" : "Физика",
      "mark" : 9
    }, {
      "subject" : "Химия",
      "mark" : 9
    } ],
    "credits" : [ {
      "subject" : "Физкультура",
      "passed" : true
    } ],
    "averageMark" : 9.0
  }, {
    "number" : 2,
    "course" : 1,
    "exams" : [ {
      "subject" : "Математика",
      "mark" : 10
    }, {
      "subject" : "Информатика",
      "mark" : 9
    } ],
    "credits" : [ {
      "subject" : "Физкультура",
      "passed" : true
    } ],
    "averageMark" : 9.5
  } ]
} ]
